# Archivo: .github/workflows/test_and_deploy.yml
name: CI Workflow

# El workflow se ejecutará en cada push o pull request a la rama 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definir los trabajos que se ejecutarán
jobs:
  test:
    runs-on: ubuntu-latest  # Usamos Ubuntu como sistema operativo en la máquina virtual

    steps:
    # Paso 1: Chequear el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Puedes cambiar la versión de Python según necesites

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Paso 4: Ejecutar pruebas automáticas
    - name: Run tests
      run: |
        pytest
